# Generated by Django 6.0.8 on 2026-08-11 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLoginExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('empresa_nombre', models.CharField(blank=True, help_text='Nombre de la empresa al momento del login (histórico).', max_length=255)),
                ('oid', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logins_externos', to='maestro.empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logins_externos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de login externo',
                'verbose_name_plural': 'Registros de login externos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
