# Generated by Django 6.0.8 on 2026-08-18 15:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0002_registrologinexterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Principio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.TextField()),
                ('suma_ponderacion', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Suma de las ponderaciones de los criterios asociados.', max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='principios', to='maestro.tema')),
            ],
            options={
                'verbose_name': 'Principio',
                'verbose_name_plural': 'Principios',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.TextField()),
                ('ponderacion', models.DecimalField(decimal_places=4, max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('principio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterios', to='maestro.principio')),
                ('tema', models.ForeignKey(help_text='Denormalizado desde el principio para facilitar consultas.', on_delete=django.db.models.deletion.PROTECT, related_name='criterios', to='maestro.tema')),
            ],
            options={
                'verbose_name': 'Criterio',
                'verbose_name_plural': 'Criterios',
                'ordering': ['codigo'],
            },
        ),
    ]
