# Generated by Django 5.2 on 2026-08-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0003_tema_principio_criterio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['codigo'],
            },
        ),
    ]
