# Generated by Django 5.2 on 2026-08-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0005_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=64)),
                ('origen', models.CharField(choices=[('CATALOGO', 'Catálogo'), ('PROPIO', 'Propio')], default='PROPIO', max_length=16)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(blank=True, help_text='Referencia al catálogo estándar, si aplica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_documento', to='maestro.documento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='maestro.empresa')),
            ],
            options={
                'verbose_name': 'Documento de empresa',
                'verbose_name_plural': 'Documentos de empresa',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaDocumentoCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_empresa_documento', to='maestro.area')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_empresa_documento', to='maestro.criterio')),
                ('empresa_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_criterio', to='maestro.empresadocumento')),
            ],
            options={
                'verbose_name': 'Vínculo documento-criterio',
                'verbose_name_plural': 'Vínculos documento-criterio',
                'ordering': ['criterio__codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='empresadocumento',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='maestro_empresadoc_empresa_codigo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='empresadocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('documento__isnull', False)), fields=('empresa', 'documento'), name='maestro_empresadoc_empresa_documento_uniq'),
        ),
        migrations.AddConstraint(
            model_name='empresadocumentocriterio',
            constraint=models.UniqueConstraint(fields=('empresa_documento', 'criterio'), name='maestro_empresadoccrit_doc_criterio_uniq'),
        ),
    ]
