# Generated by Django 5.2 on 2026-08-31 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0007_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_estandar', to='maestro.criterio')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_estandar', to='maestro.documento')),
            ],
            options={
                'verbose_name': 'Relación estándar documento-criterio',
                'verbose_name_plural': 'Relaciones estándar documento-criterio',
                'ordering': ['documento__codigo', 'criterio__codigo'],
                'constraints': [models.UniqueConstraint(fields=('documento', 'criterio'), name='maestro_documentocriterio_doc_crit_uniq')],
            },
        ),
    ]
